/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bugtracker;

import java.util.logging.Logger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	Integer a = new Integer(1);
    	
       
    }
}
